/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CalculatorController;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 * Contain user interface
 *
 * @author pc
 */
public class CalculatorView extends javax.swing.JFrame {

    private CalculatorController controller;

    /**
     * Constructor of class
     */
    public CalculatorView() {
        initComponents();
        controller = new CalculatorController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDisplay = new javax.swing.JTextField();
        btnMC = new javax.swing.JButton();
        btnNum7 = new javax.swing.JButton();
        btnNum4 = new javax.swing.JButton();
        btnNum1 = new javax.swing.JButton();
        btnNum0 = new javax.swing.JButton();
        btnMR = new javax.swing.JButton();
        btnNum8 = new javax.swing.JButton();
        btnNum5 = new javax.swing.JButton();
        btnNum2 = new javax.swing.JButton();
        btnDot = new javax.swing.JButton();
        btnMAdd = new javax.swing.JButton();
        btnNum9 = new javax.swing.JButton();
        btnNum6 = new javax.swing.JButton();
        btnNum3 = new javax.swing.JButton();
        btnMSub = new javax.swing.JButton();
        btnDiv = new javax.swing.JButton();
        btnMulti = new javax.swing.JButton();
        btnSub = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnSquareRoot = new javax.swing.JButton();
        btnPercent = new javax.swing.JButton();
        btnFlip = new javax.swing.JButton();
        btnEqual = new javax.swing.JButton();
        btnNegate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");

        txtDisplay.setEditable(false);
        txtDisplay.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDisplay.setText("0");

        btnMC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnMC.setText("MC");
        btnMC.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnMC.setPreferredSize(new java.awt.Dimension(40, 40));
        btnMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMCActionPerformed(evt);
            }
        });

        btnNum7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNum7.setText("7");
        btnNum7.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnNum7.setPreferredSize(new java.awt.Dimension(40, 40));

        btnNum4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNum4.setText("4");
        btnNum4.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnNum4.setPreferredSize(new java.awt.Dimension(40, 40));

        btnNum1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNum1.setText("1");
        btnNum1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnNum1.setPreferredSize(new java.awt.Dimension(40, 40));

        btnNum0.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNum0.setText("0");
        btnNum0.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnNum0.setPreferredSize(new java.awt.Dimension(40, 40));

        btnMR.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnMR.setText("MR");
        btnMR.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnMR.setPreferredSize(new java.awt.Dimension(40, 40));
        btnMR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMRActionPerformed(evt);
            }
        });

        btnNum8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNum8.setText("8");
        btnNum8.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnNum8.setPreferredSize(new java.awt.Dimension(40, 40));

        btnNum5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNum5.setText("5");
        btnNum5.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnNum5.setPreferredSize(new java.awt.Dimension(40, 40));

        btnNum2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNum2.setText("2");
        btnNum2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnNum2.setPreferredSize(new java.awt.Dimension(40, 40));

        btnDot.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDot.setText(".");
        btnDot.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnDot.setPreferredSize(new java.awt.Dimension(40, 40));
        btnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDotActionPerformed(evt);
            }
        });

        btnMAdd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnMAdd.setText("M+");
        btnMAdd.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnMAdd.setPreferredSize(new java.awt.Dimension(40, 40));
        btnMAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMAddActionPerformed(evt);
            }
        });

        btnNum9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNum9.setText("9");
        btnNum9.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnNum9.setPreferredSize(new java.awt.Dimension(40, 40));

        btnNum6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNum6.setText("6");
        btnNum6.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnNum6.setPreferredSize(new java.awt.Dimension(40, 40));

        btnNum3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNum3.setText("3");
        btnNum3.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnNum3.setPreferredSize(new java.awt.Dimension(40, 40));

        btnMSub.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnMSub.setText("M-");
        btnMSub.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnMSub.setPreferredSize(new java.awt.Dimension(40, 40));
        btnMSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMSubActionPerformed(evt);
            }
        });

        btnDiv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDiv.setText("/");
        btnDiv.setActionCommand("Div");
        btnDiv.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnDiv.setPreferredSize(new java.awt.Dimension(40, 40));
        btnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivActionPerformed(evt);
            }
        });

        btnMulti.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnMulti.setText("x");
        btnMulti.setActionCommand("Multi");
        btnMulti.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnMulti.setPreferredSize(new java.awt.Dimension(40, 40));
        btnMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiActionPerformed(evt);
            }
        });

        btnSub.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSub.setText("-");
        btnSub.setActionCommand("Sub");
        btnSub.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnSub.setPreferredSize(new java.awt.Dimension(40, 40));
        btnSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubActionPerformed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAdd.setText("+");
        btnAdd.setActionCommand("Add");
        btnAdd.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnAdd.setPreferredSize(new java.awt.Dimension(40, 40));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnSquareRoot.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSquareRoot.setText("√");
        btnSquareRoot.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnSquareRoot.setPreferredSize(new java.awt.Dimension(40, 40));
        btnSquareRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSquareRootActionPerformed(evt);
            }
        });

        btnPercent.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPercent.setText("%");
        btnPercent.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnPercent.setPreferredSize(new java.awt.Dimension(40, 40));
        btnPercent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPercentActionPerformed(evt);
            }
        });

        btnFlip.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnFlip.setText("1/x");
        btnFlip.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnFlip.setPreferredSize(new java.awt.Dimension(40, 40));
        btnFlip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlipActionPerformed(evt);
            }
        });

        btnEqual.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEqual.setText("=");
        btnEqual.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnEqual.setPreferredSize(new java.awt.Dimension(40, 40));
        btnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualActionPerformed(evt);
            }
        });

        btnNegate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNegate.setText("+/-");
        btnNegate.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnNegate.setPreferredSize(new java.awt.Dimension(40, 40));
        btnNegate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNegateActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDisplay, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnNum7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnNum8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnNum9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnPercent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnNum4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnNum5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnNum6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnMulti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnFlip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnNum0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnDot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnNegate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnNum3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(18, 18, 18)
                                    .addComponent(btnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnMC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnMR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnMAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnMSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnSquareRoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnClear, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSquareRoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNum7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPercent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNum4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMulti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFlip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNum3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNum0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNegate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Handle event of MR button
     *
     * @param evt Object of <Code>java.awt.event.ActionEvent</Code>
     */
    private void btnMRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMRActionPerformed
        controller.mRes();
    }//GEN-LAST:event_btnMRActionPerformed

    /**
     * Handle event of M+ button
     *
     * @param evt Object of <Code>java.awt.event.ActionEvent</Code>
     */
    private void btnMAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMAddActionPerformed
        controller.mAdd();
    }//GEN-LAST:event_btnMAddActionPerformed

    /**
     * Handle event of MC button
     *
     * @param evt Object of <Code>java.awt.event.ActionEvent</Code>
     */
    private void btnMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMCActionPerformed
        controller.mClear();
    }//GEN-LAST:event_btnMCActionPerformed

    /**
     * Handle event of M- button
     *
     * @param evt Object of <Code>java.awt.event.ActionEvent</Code>
     */
    private void btnMSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMSubActionPerformed
        controller.mSub();
    }//GEN-LAST:event_btnMSubActionPerformed

    /**
     * Handle event of Sqrt button
     *
     * @param evt Object of <Code>java.awt.event.ActionEvent</Code>
     */
    private void btnSquareRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSquareRootActionPerformed
        controller.sqrt();
    }//GEN-LAST:event_btnSquareRootActionPerformed

    /**
     * Handle event of % button
     *
     * @param evt Object of <Code>java.awt.event.ActionEvent</Code>
     */
    private void btnPercentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPercentActionPerformed
        controller.percentile();
    }//GEN-LAST:event_btnPercentActionPerformed

    /**
     * Handle event of Invert button
     *
     * @param evt Object of <Code>java.awt.event.ActionEvent</Code>
     */
    private void btnFlipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlipActionPerformed
        controller.invert();
    }//GEN-LAST:event_btnFlipActionPerformed

    /**
     * Handle event of Equal button
     *
     * @param evt Object of <Code>java.awt.event.ActionEvent</Code>
     */
    private void btnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualActionPerformed
        controller.perform();
    }//GEN-LAST:event_btnEqualActionPerformed

    /**
     * Handle event of Divide button
     *
     * @param evt Object of <Code>java.awt.event.ActionEvent</Code>
     */
    private void btnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivActionPerformed
        controller.setOperator('/');
    }//GEN-LAST:event_btnDivActionPerformed

    /**
     * Handle event of Multiply button
     *
     * @param evt Object of <Code>java.awt.event.ActionEvent</Code>
     */
    private void btnMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiActionPerformed
        controller.setOperator('*');
    }//GEN-LAST:event_btnMultiActionPerformed

    /**
     * Handle event of Subtract button
     *
     * @param evt Object of <Code>java.awt.event.ActionEvent</Code>
     */
    private void btnSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubActionPerformed
        controller.setOperator('-');
    }//GEN-LAST:event_btnSubActionPerformed

    /**
     * Handle event of Add button
     *
     * @param evt Object of <Code>java.awt.event.ActionEvent</Code>
     */
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        controller.setOperator('+');
    }//GEN-LAST:event_btnAddActionPerformed

    /**
     * Handle event of Negate button
     *
     * @param evt Object of <Code>java.awt.event.ActionEvent</Code>
     */
    private void btnNegateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNegateActionPerformed
        controller.negate();
    }//GEN-LAST:event_btnNegateActionPerformed

    /**
     * Handle event of Dot button
     *
     * @param evt Object of <Code>java.awt.event.ActionEvent</Code>
     */
    private void btnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDotActionPerformed
        controller.addDot();
    }//GEN-LAST:event_btnDotActionPerformed

    /**
     * Handle event of Clear button
     *
     * @param evt Object of <Code>java.awt.event.ActionEvent</Code>
     */
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        controller.clear();
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorView().setVisible(true);
            }
        });
    }

    /**
     * Get the controller class
     *
     * @return The object of <Code>controller.CalculatorController</Code>
     */
    public CalculatorController getController() {
        return controller;
    }

    /**
     * Set controller class to given Controller
     *
     * @param c Object of <Code>controller.CalculatorController</Code>
     */
    public void setController(CalculatorController c) {
        this.controller = c;
    }

    /**
     * Get button number 0
     *
     * @return object of <Code>javax.swing.JButton</Code>
     */
    public JButton getBtnNum0() {
        return btnNum0;
    }

    /**
     * Get button number 1
     *
     * @return object of <Code>javax.swing.JButton</Code>
     */
    public JButton getBtnNum1() {
        return btnNum1;
    }

    /**
     * Get button number 2
     *
     * @return object of <Code>javax.swing.JButton</Code>
     */
    public JButton getBtnNum2() {
        return btnNum2;
    }

    /**
     * Get button number 3
     *
     * @return object of <Code>javax.swing.JButton</Code>
     */
    public JButton getBtnNum3() {
        return btnNum3;
    }

    /**
     * Get button number 4
     *
     * @return object of <Code>javax.swing.JButton</Code>
     */
    public JButton getBtnNum4() {
        return btnNum4;
    }

    /**
     * Get button number 5
     *
     * @return object of <Code>javax.swing.JButton</Code>
     */
    public JButton getBtnNum5() {
        return btnNum5;
    }

    /**
     * Get button number 6
     *
     * @return object of <Code>javax.swing.JButton</Code>
     */
    public JButton getBtnNum6() {
        return btnNum6;
    }

    /**
     * Get button number 7
     *
     * @return object of <Code>javax.swing.JButton</Code>
     */
    public JButton getBtnNum7() {
        return btnNum7;
    }

    /**
     * Get button number 8
     *
     * @return object of <Code>javax.swing.JButton</Code>
     */
    public JButton getBtnNum8() {
        return btnNum8;
    }

    /**
     * Get button number 9
     *
     * @return object of <Code>javax.swing.JButton</Code>
     */
    public JButton getBtnNum9() {
        return btnNum9;
    }

    /**
     * Set equal button to given button
     *
     * @param btnEqual object of <Code>javax.swing.JButton</Code>
     */
    public void setBtnEqual(JButton btnEqual) {
        this.btnEqual = btnEqual;
    }

    /**
     * Set negate button to given button
     *
     * @param btnNegate object of <Code>javax.swing.JButton</Code>
     */
    public void setBtnNegate(JButton btnNegate) {
        this.btnNegate = btnNegate;
    }

    /**
     * Set number 0 button to given button
     *
     * @param btnNum0 object of <Code>javax.swing.JButton</Code>
     */
    public void setBtnNum0(JButton btnNum0) {
        this.btnNum0 = btnNum0;
    }

    /**
     * Set number 1 button to given button
     *
     * @param btnNum1 object of <Code>javax.swing.JButton</Code>
     */
    public void setBtnNum1(JButton btnNum1) {
        this.btnNum1 = btnNum1;
    }

    /**
     * Set number 2 button to given button
     *
     * @param btnNum2 object of <Code>javax.swing.JButton</Code>
     */
    public void setBtnNum2(JButton btnNum2) {
        this.btnNum2 = btnNum2;
    }

    /**
     * Set number 3 button to given button
     *
     * @param btnNum3 object of <Code>javax.swing.JButton</Code>
     */
    public void setBtnNum3(JButton btnNum3) {
        this.btnNum3 = btnNum3;
    }

    /**
     * Set number 4 button to given button
     *
     * @param btnNum4 object of <Code>javax.swing.JButton</Code>
     */
    public void setBtnNum4(JButton btnNum4) {
        this.btnNum4 = btnNum4;
    }

    /**
     * Set number 5 button to given button
     *
     * @param btnNum5 object of <Code>javax.swing.JButton</Code>
     */
    public void setBtnNum5(JButton btnNum5) {
        this.btnNum5 = btnNum5;
    }

    /**
     * Set number 6 button to given button
     *
     * @param btnNum6 object of <Code>javax.swing.JButton</Code>
     */
    public void setBtnNum6(JButton btnNum6) {
        this.btnNum6 = btnNum6;
    }

    /**
     * Set number 7 button to given button
     *
     * @param btnNum7 object of <Code>javax.swing.JButton</Code>
     */
    public void setBtnNum7(JButton btnNum7) {
        this.btnNum7 = btnNum7;
    }

    /**
     * Set number 8 button to given button
     *
     * @param btnNum8 object of <Code>javax.swing.JButton</Code>
     */
    public void setBtnNum8(JButton btnNum8) {
        this.btnNum8 = btnNum8;
    }

    /**
     * Set number 9 button to given button
     *
     * @param btnNum9 object of <Code>javax.swing.JButton</Code>
     */
    public void setBtnNum9(JButton btnNum9) {
        this.btnNum9 = btnNum9;
    }

    /**
     * Get button operate +
     *
     * @return object of <Code>javax.swing.JButton</Code>
     */
    public JButton getBtnAdd() {
        return btnAdd;
    }

    /**
     * Set button operate '+' to given button
     *
     * @param btnAdd object of <Code>javax.swing.JButton</Code>
     */
    public void setBtnAdd(JButton btnAdd) {
        this.btnAdd = btnAdd;
    }

    /**
     * Get button Clear
     *
     * @return object of <Code>javax.swing.JButton</Code>
     */
    public JButton getBtnClear() {
        return btnClear;
    }

    /**
     * Set button clear to given button
     *
     * @param btnClear object of <Code>javax.swing.JButton</Code>
     */
    public void setBtnClear(JButton btnClear) {
        this.btnClear = btnClear;
    }

    /**
     * Get button operate /
     *
     * @return object of <Code>javax.swing.JButton</Code>
     */
    public JButton getBtnDiv() {
        return btnDiv;
    }

    /**
     * Set divide button to given button
     *
     * @param btnDiv object of <Code>javax.swing.JButton</Code>
     */
    public void setBtnDiv(JButton btnDiv) {
        this.btnDiv = btnDiv;
    }

    /**
     * Get button dot
     *
     * @return object of <Code>javax.swing.JButton</Code>
     */
    public JButton getBtnDot() {
        return btnDot;
    }

    /**
     * Set dot button to given button
     *
     * @param btnDot object of <Code>javax.swing.JButton</Code>
     */
    public void setBtnDot(JButton btnDot) {
        this.btnDot = btnDot;
    }

    /**
     * Get button 1/x
     *
     * @return object of <Code>javax.swing.JButton</Code>
     */
    public JButton getBtnFlip() {
        return btnFlip;
    }

    /**
     * Set 1/x button to given button
     *
     * @param btnFlip object of <Code>javax.swing.JButton</Code>
     */
    public void setBtnFlip(JButton btnFlip) {
        this.btnFlip = btnFlip;
    }

    /**
     * Get button M+
     *
     * @return object of <Code>javax.swing.JButton</Code>
     */
    public JButton getBtnMAdd() {
        return btnMAdd;
    }

    /**
     * Set + button to given button
     *
     * @param btnMAdd object of <Code>javax.swing.JButton</Code>
     */
    public void setBtnMAdd(JButton btnMAdd) {
        this.btnMAdd = btnMAdd;
    }

    /**
     * Get button MC
     *
     * @return object of <Code>javax.swing.JButton</Code>
     */
    public JButton getBtnMC() {
        return btnMC;
    }

    /**
     * Set MC button to given button
     *
     * @param btnMC object of <Code>javax.swing.JButton</Code>
     */
    public void setBtnMC(JButton btnMC) {
        this.btnMC = btnMC;
    }

    /**
     * Get button MR
     *
     * @return object of <Code>javax.swing.JButton</Code>
     */
    public JButton getBtnMR() {
        return btnMR;
    }

    /**
     * Set MR button to given button
     *
     * @param btnMR object of <Code>javax.swing.JButton</Code>
     */
    public void setBtnMR(JButton btnMR) {
        this.btnMR = btnMR;
    }

    /**
     * Get button M-
     *
     * @return object of <Code>javax.swing.JButton</Code>
     */
    public JButton getBtnMSub() {
        return btnMSub;
    }

    /**
     * Set M- button to given button
     *
     * @param btnMSub object of <Code>javax.swing.JButton</Code>
     */
    public void setBtnMSub(JButton btnMSub) {
        this.btnMSub = btnMSub;
    }

    /**
     * Get button operate *
     *
     * @return object of <Code>javax.swing.JButton</Code>
     */
    public JButton getBtnMulti() {
        return btnMulti;
    }

    /**
     * Set * button to given button
     *
     * @param btnMulti object of <Code>javax.swing.JButton</Code>
     */
    public void setBtnMulti(JButton btnMulti) {
        this.btnMulti = btnMulti;
    }

    /**
     * Get button %
     *
     * @return object of <Code>javax.swing.JButton</Code>
     */
    public JButton getBtnPercent() {
        return btnPercent;
    }

    /**
     * Set % button to given button
     *
     * @param btnPercent object of <Code>javax.swing.JButton</Code>
     */
    public void setBtnPercent(JButton btnPercent) {
        this.btnPercent = btnPercent;
    }

    /**
     * Get button =
     *
     * @return object of <Code>javax.swing.JButton</Code>
     */
    public JButton getBtnPerform() {
        return btnEqual;
    }

    /**
     * Set = button to given button
     *
     * @param btnPerform object of <Code>javax.swing.JButton</Code>
     */
    public void setBtnPerform(JButton btnPerform) {
        this.btnEqual = btnPerform;
    }

    /**
     * Get button square root
     *
     * @return object of <Code>javax.swing.JButton</Code>
     */
    public JButton getBtnSquareRoot() {
        return btnSquareRoot;
    }

    /**
     * Set square root button to given button
     *
     * @param btnSquareRoot object of <Code>javax.swing.JButton</Code>
     */
    public void setBtnSquareRoot(JButton btnSquareRoot) {
        this.btnSquareRoot = btnSquareRoot;
    }

    /**
     * Get button operate -
     *
     * @return object of <Code>javax.swing.JButton</Code>
     */
    public JButton getBtnSub() {
        return btnSub;
    }

    /**
     * Set - button to given button
     *
     * @param btnSub object of <Code>javax.swing.JButton</Code>
     */
    public void setBtnSub(JButton btnSub) {
        this.btnSub = btnSub;
    }

    /**
     * Get button +/-
     *
     * @return object of <Code>javax.swing.JButton</Code>
     */
    public JButton getBtnSwap() {
        return btnNegate;
    }

    /**
     * Set +/- button to given button
     *
     * @param btnSwap object of <Code>javax.swing.JButton</Code>
     */
    public void setBtnSwap(JButton btnSwap) {
        this.btnNegate = btnSwap;
    }

    /**
     * Get screen display
     *
     * @return object of <Code>javax.swing.JTextField</Code>
     */
    public JTextField getTxtDisplay() {
        return txtDisplay;
    }

    /**
     * Set screen display to given display
     *
     * @param txtDisplay Object of <Code>javax.swing.JTextField</Code>
     */
    public void setTxtDisplay(JTextField txtDisplay) {
        CalculatorView.txtDisplay = txtDisplay;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDiv;
    private javax.swing.JButton btnDot;
    public javax.swing.JButton btnEqual;
    private javax.swing.JButton btnFlip;
    private javax.swing.JButton btnMAdd;
    public javax.swing.JButton btnMC;
    public javax.swing.JButton btnMR;
    private javax.swing.JButton btnMSub;
    private javax.swing.JButton btnMulti;
    private javax.swing.JButton btnNegate;
    private javax.swing.JButton btnNum0;
    private javax.swing.JButton btnNum1;
    private javax.swing.JButton btnNum2;
    private javax.swing.JButton btnNum3;
    private javax.swing.JButton btnNum4;
    private javax.swing.JButton btnNum5;
    private javax.swing.JButton btnNum6;
    private javax.swing.JButton btnNum7;
    private javax.swing.JButton btnNum8;
    private javax.swing.JButton btnNum9;
    private javax.swing.JButton btnPercent;
    private javax.swing.JButton btnSquareRoot;
    private javax.swing.JButton btnSub;
    public static javax.swing.JTextField txtDisplay;
    // End of variables declaration//GEN-END:variables

}
